### ISSUE TITLE
Update package to version 1.87.0

### ISSUE THREAD

**Issue by uriklar** [eliagrady/wix-sdk#2]
Hi! The UI-lib docs state a dependency on ```<script src="//static.parastorage.com/services/js-sdk/1.87.0/js/wix.min.js"></script>```

Can you update this package to include this version of the sdk?
Thanks!
Uri

**Comment by eliagrady** [comment]
I'll add documentation on how to use the feature that chooses a Wix SDK version ('npm run update').
Version is now up-to-date.
